version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: findr
      POSTGRES_USER: findr
      POSTGRES_PASSWORD: findr
    ports:
      - 5436:5432
    volumes:
      - ./001-init.sql:/docker-entrypoint-initdb.d/001-init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
