version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: findr
      POSTGRES_USER: findr
      POSTGRES_PASSWORD: findr
    ports:
      - 5436:5432
    volumes:
      - ./001-init.sql:/docker-entrypoint-initdb.d/001-init.sql
      - ./002-timestamp-triggers.sql:/docker-entrypoint-initdb.d/002-timestamp-triggers.sql
      - ./003-cleanup.sql:/docker-entrypoint-initdb.d/003-cleanup.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
